### ISSUE TITLE
Review Lab1:Task 5

### ISSUE THREAD

**Issue by RoodeyMental** [sweIhm-ws2018-19/skillproject-fr-34#15]
Please review Task 5 of Lab 1.

**Comment by Tosaa** [comment]
Couldn't open XML-Code in draw.io
Please add closing " in bezeichnung of kontoHans:Konto and in nachname in LieseMüller:Privatkunde.
I would recomend to use the same amount of spaces all the time also. 
May add Space before and after = sign at beizeichnung in kontoHans and kontoLiese.
I am not sure if "Bewohner" is the right property between "Geschäftskunde" and "Domiziladresse". "Firmensitz" sounds better i guess.

**Comment by RoodeyMental** [comment]
Added your changes, thanks for the reply.
