### ISSUE TITLE
Lab 1 Task 4 Evaluation

### ISSUE THREAD

**Issue by RoodeyMental** [sweIhm-ws2018-19/skillproject-fr-34#18]
Dear Ms. Prof. Dr. Socher,
please evaluate Task 4 of Lab 1 once more.

**Comment by RoodeyMental** [comment]
Link to Wiki Page: https://github.com/sweIhm-ws2018-19/skillproject-fr-34/wiki/Lab1

**Comment by gsocher** [comment]
done on Dienstag, 6. November 2018, 18:36 Uhr, closing now.
