### ISSUE TITLE
Fragen aus einer Kategorie:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#22]
Als Spieler möchte ich mich in einem bestimmten Themenbereich verbessern und deshalb Fragen aus einer Kategorie meiner Wahl gestellt bekommen. Sobald ich eine bestimme Kategorie trainieren kann, ist die Anforderung erfüllt.

**Comment by RoodeyMental** [comment]
fragen werden gefiltert und passende frage ausgeben. Siehe getNextQuestion in GameUtil klasse

**Comment by RoodeyMental** [comment]
please review

**Comment by Tosaa** [comment]
Die Fragen werden aus der Datenbank gelesen und sobald die Kategorie und Schwierigkeit gesetzt sind, zur Verfügung gestellt. Die Fragen kommen aus einer bestimmten Kategorie.
