### ISSUE TITLE
Fragen bestimmer Schwierigkeit: 

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#24]
Ich als Spieler möchte Fragen gestellt bekommen, die meinem Level an Allgemeinwissen entsprechen. Diese Anforderung ist erfüllt, wenn ich den Schwierigkeitsgrad meinem Wissensstand anpassen kann.

**Comment by RoodeyMental** [comment]
Methode in GameUtil Klasse. Fragen werden erst aus db ausgelesen, nach kategorie und schwierigkeit gefiltert und mittels get nextQuestion methode eine zufällige frage aus dem pool ausgelesen.

**Comment by RoodeyMental** [comment]
please review

**Comment by Tosaa** [comment]
Die Fragen werden aus der Datenbank gelesen und sobald die Kategorie und Schwierigkeit gesetzt sind, zur Verfügung gestellt. Die Fragen kommen aus einer bestimmten Schwierigkeit.
