### ISSUE TITLE
Lösungshinweise:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#25]
Als Spieler kommt es vor, dass ich eine gestellte Frage nicht exakt beantworten kann, ich aber eine Vermutung habe. In diesem Fall möchte ich mir einen Lösungshinweis ausgeben lassen können oder eine Reihe an Antwortmöglichkeiten. Die Funktionalität ist gegeben wenn ich eine Hilfestellung zur Lösung einer Frage bekomme.

**Comment by RoodeyMental** [comment]
Lösungshinweise (lösungsmöglichkeit oder hinweis) wird über den HelpMe Intent ausgegeben. Dazu wurde eine HelpMeIntent klasse hinzugefügt, die entsprechende Infos aus currentQuestion ausliest und ausgibt

**Comment by RoodeyMental** [comment]
please review

**Comment by Tosaa** [comment]
Lösungshinweise sowie Antwortmöglichkeiten werden aus der Datenbank gelesen und stehen zur verfügung. Der Spieler kann sich diese dann ausgeben lassen.
