### ISSUE TITLE
Score nach dem Spiel:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#26]
Um meine Leistung als Spieler besser einschätzen zu können möchte ich nach einem Spiel meine erreichten Punkte / Anzahl richtig beantworteter Fragen ausgeben lassen. Die Anforderung ist erfüllt wenn, ich nach einem Spiel meine Leistung in Form von meinem Score mitgeteilt bekomme.

**Comment by Tosaa** [comment]
Das Spiel ist nach 10 Fragen zu ende, oder sobald der Spieler sich verabschiedet. 
Beendet der Spieler vorzeitig (vor 10 gestellten Fragen) das Spiel, so bekommt er die Anzahl der richtigen Fragen gut geschrieben. Die Anzahl der gefragten Fragen wird bei 10 belassen. Auch wenn nur 5 gestellt wurden.
siehe Sitzung 21.12 https://github.com/sweIhm-ws2018-19/skillproject-fr-34/wiki/Sprint_3

**Comment by RoodeyMental** [comment]
Nach einem Spiel ( also 10 Fragen ) werden nun die erreichten Punkte, also die Anzahl der richtig beantworteten fragen, ausgegeben. Bitte reviewen und Funkionalität bestätigen.

**Comment by Tosaa** [comment]
funktioniert
