### ISSUE TITLE
Highscore:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#28]
Ich als Spieler möchte wissen was meine beste, jemals erzielte Leistung ist. Dies ist erfüllt wenn ich auf Abruf meinen Highscore ausgegeben bekomme.

**Comment by Tosaa** [comment]
Es wird nur der Highscore ausgegeben, der am besten war.
siehe https://github.com/sweIhm-ws2018-19/skillproject-fr-34/wiki/Sprint_3
Optional: 
Highscore des letzten spiels kann ausgegeben werden.

**Comment by Tosaa** [comment]
Highscore bedeutet Anzahl der gestellten Fragen und Anzahl der Richtigen Fragen.
Gestellte Fragen sind immer 10.
Richtige Fragen werden erhöht wenn der Spieler eine Frage richtig beantwortet hat.

**Comment by RoodeyMental** [comment]
HIghscore macht bei dem aktuellen System keinen Sinn, da sobald einmal 10/10 Fragen richtig beantwortet wurden, immer Highscore 10 ausgegeben wird und man sich quasi nicht mehr verbessern kann. Daher wurde stattdessen, eine Funktion eingebaut, die einem die letzten 3 Punktestände ausgibt.
