### ISSUE TITLE
Spiel Abbrechen:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#29]
Ich als Spieler möchte das Spiel abbrechen können, wenn ich z.B. keine Lust oder Zeit mehr habe. Dies ist erfüllt wenn ich das Spiel jederzeit abbrechen kann.

**Comment by RoodeyMental** [comment]
Erledigt

**Comment by RoodeyMental** [comment]
"schließe test your brain" beendet den kill, alexa verabschiedet sich.

**Comment by RoodeyMental** [comment]
please review

**Comment by Tosaa** [comment]
Später müssen wir noch den Spielstand abspeichern. Für diesen Sprint aber in Ordnung.
