### ISSUE TITLE
Kategorie wechseln:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#30]
Als Spieler möchte ich selbstständig die Kategorie der Fragen wechseln können. Diese Funktionalität ist gegeben, wenn ich durch einen Befehl die Kategorie der Fragen wechseln kann und danach nur noch Fragen einer anderen bestimmten Kategorie erhalte.

**Comment by RoodeyMental** [comment]
Funktionalität wurde umgesetzt.

**Comment by RoodeyMental** [comment]
Please Review

**Comment by Tosaa** [comment]
Die Funktionalität ist Implementiert und unter https://github.com/sweIhm-ws2018-19/skillproject-fr-34/wiki/Sprint_1 zu finden
