### ISSUE TITLE
Schwierigkeit wechseln:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#31]
Als Spieler möchte ich selbstständig die Schwierigkeit der Fragen wechseln können. Diese Funktionalität ist gegeben, wenn ich durch einen Befehl die Schwierigkeit der Fragen wechseln kann und danach nur noch Fragen einer anderen Schwierigkeit erhalte.

**Comment by RoodeyMental** [comment]
Funktion wurde in Klasse: SelectDifficultyIntent Klasse umgesetzt

**Comment by RoodeyMental** [comment]
Please Review

**Comment by Tosaa** [comment]
Die Funktionalität ist Implementiert und unter https://github.com/sweIhm-ws2018-19/skillproject-fr-34/wiki/Sprint_1 zu finden
