### ISSUE TITLE
Richtige und falsche Anworten am Klang erkennen:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#32]
Als Spieler möchte ich anhand eines Sound-effekts erkennen ob meine Antwort richtig oder falsch war, bevor mir die Antwort gesagt wird. Diese Funktionalität ist gegeben, wenn nach meiner Antwort ein Geräusch ertönt an dem ich erkennen kann ob meine Antwort richtig oder falsch war.

**Comment by Tosaa** [comment]
Ein Geräusch der Amazon Sound Libary wird abgespielt wenn der Spieler eine Antwort eingibt. Für die richtige Eingabe ertönt ein Geräusch und für die falsche Eingabe ein anderes. Dadurch weiß der Spieler sofort ob seine Angabe richtig war.

**Comment by Tosaa** [comment]
töne habe ich von hier:
https://developer.amazon.com/de/docs/custom-skills/ui-gameshow-sounds.html

**Comment by RoodeyMental** [comment]
Review: Anforderungen umgesetzt, funktioniert wunderbar -> closed.
