### ISSUE TITLE
Antwort eingeben:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#33]
Auf eine Frage möchte ich eine Antwort geben können. Diese Funktionalität ist gegeben, wenn ich nach einer Frage Zeit habe um mir eine Antwort zu überlegen und diese Alexa mitteilen kann.

**Comment by RoodeyMental** [comment]
Antwort kann eingegeben werden mittels "Antwort xxx" Auslöser. Diese wird dann überprüft und das ergebnis ausgegeben

**Comment by RoodeyMental** [comment]
please review

**Comment by Tosaa** [comment]
Es ist möglich Fragen zu beantworten, sowohl mit Richtigen sowie mit falschen Eingaben.
