### ISSUE TITLE
Frage wiederholen:

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#34]
Als Spieler möchte ich mir eine Frage noch einmal anhören können. Diese Funktionalität ist gegeben, wenn ich Alexa mitteilen kann, dass ich die Frage erneut hören möchte und sie die Frage wiederholt.

**Comment by RoodeyMental** [comment]
RepeadQuestion Intent + Handler erstellt. Frage wird nun wiedholt wenn gesagt wird "wiederhole die frage"

**Comment by RoodeyMental** [comment]
please review

**Comment by Tosaa** [comment]
Bei Missverständnissen oder Unklarheiten, kann sich der Spieler die Frage wiederholen lassen.
