### ISSUE TITLE
Spielregeln erklären lassen:

### ISSUE THREAD

**Issue by RoodeyMental** [sweIhm-ws2018-19/skillproject-fr-34#39]
Wenn ich als Spieler den Skill z.B. zum ersten Mal starte möchte ich gerne die Spielregeln erklärt bekommen. Die Anforderung ist erfüllt, wenn ich eine verständliche Erklärung der Spielregeln erhalte.

**Comment by RoodeyMental** [comment]
Funktion umgesetzt, nur Ausgabe in LaunchRequestHandler muss noch angepasst werden. StartGameIntent ist dadurch obsolet.

**Comment by RoodeyMental** [comment]
erledigt

**Comment by RoodeyMental** [comment]
please review

**Comment by Tosaa** [comment]
Wird beim Starten des Skills ausgeführt.
