### ISSUE TITLE
Initiale Kategorie einstellen

### ISSUE THREAD

**Issue by RoodeyMental** [sweIhm-ws2018-19/skillproject-fr-34#42]
Als Spieler möchte ich vor dem eigentlichen Spiel einstellen können, aus welcher Kategorie die mir gestellten Fragen sein werden. Die Anforderung ist erfüllt wenn vor der ersten Frage die gewünschte Kategorie gewählt werden kann.

**Comment by RoodeyMental** [comment]
Funktion wurde in Klasse: InsertCategoryIntent umgesetzt

**Comment by RoodeyMental** [comment]
Please Review

**Comment by Tosaa** [comment]
Die Funktionalität ist Implementiert und unter https://github.com/sweIhm-ws2018-19/skillproject-fr-34/wiki/Sprint_1 zu finden.
Ähnelt SelectCategoryIntent. Eventuell können wir die Funktionalitäten später zusammen fügen.
