### ISSUE TITLE
Initiale Schwierigkeitsstufe einstellen

### ISSUE THREAD

**Issue by RoodeyMental** [sweIhm-ws2018-19/skillproject-fr-34#43]
Als Spieler möchte ich vor dem eigentlichen Spiel einstellen können, wie schwierig die mir gestellten Fragen sein werden. Die Anforderung ist erfüllt wenn vor der ersten Frage die gewünschte Schwierigkeitsstufe gewählt werden kann.

**Comment by RoodeyMental** [comment]
Funktion wurde in Klasse: InsertDifficultyIntent umgesetzt

**Comment by Tosaa** [comment]
Die Funktionalität ist Implementiert und unter https://github.com/sweIhm-ws2018-19/skillproject-fr-34/wiki/Sprint_1 zu finden.
Ähnelt SelectDifficultyIntent. Eventuell können wir die Funktionalitäten später zusammen fügen.
