### ISSUE TITLE
getStoryLine Vorgaben bestmöglich umsetzen

### ISSUE THREAD

**Issue by RoodeyMental** [sweIhm-ws2018-19/skillproject-fr-34#48]

**Comment by RoodeyMental** [comment]
Problem ist, dass dort sehr oft mit Ja/Nein fragen geantwortet wird, die für uns extrem ungünstig umzusetzen sind. Es muss geprüft werden ob seitens Jenny/Jessi Alternativen möglich sind oder man mittels der kürzlich eingeführten GameStates (Rules,Config,Game) diese Ja/Nein Fragen doch umsetzbar sind. Allerdings ist von Frau Socher die Vorgabe möglichst eindeutige Auslöser für unterschiedliche Intents zu finden um so das Problem zu umgehen.

**Comment by Tosaa** [comment]
Eventuell sollten wir dieses Issue auf einen späteren Sprint verlagern. Gedanken diesbezüglich können wir uns ja schon machen.

**Comment by RoodeyMental** [comment]
Ja, da hast du wohl auch recht. Allerdings ist es am Ende wahrscheinlich ein größerer vorallem wenn die 'Abzweigungen' nicht passen, da das für uns evtl neue/zusätzliche intents bedeutet. Wir sollten uns mal mit den Damen absprechen.

Von meinem Huawei-Mobiltelefon gesendet

-------- Originalnachricht --------
Betreff: Re: [sweIhm-ws2018-19/skillproject-fr-34] getStoryLine Vorgaben bestmöglich umsetzen (#48)
Von: Anton Saatze
An: sweIhm-ws2018-19/skillproject-fr-34
Cc: "Wiesheu, Markus" ,Author


Eventuell sollten wir dieses Issue auf einen späteren Sprint verlagern. Gedanken diesbezüglich können wir uns ja schon machen.

**Comment by RoodeyMental** [comment]
Mit Jessi / Jenny abgestimmt, es wird nach alternativen zu den Ja/Nein Fragen gesucht.
