### ISSUE TITLE
LaunchRequestHandler-Ausgabe anpassen ( Frage nach Regeln einbauen)

### ISSUE THREAD

**Issue by RoodeyMental** [sweIhm-ws2018-19/skillproject-fr-34#49]

**Comment by Tosaa** [comment]
Ich habe den Launch Request Handler so geändert dass am anfang gefragt wird ob man die Regeln erklärt bekommen möchte. Dadurch bleiben eigentlich nur noch die Antworten Ja und Nein übrig und durch diese wird man direkt in den Rules Intent geleitet und kann ab da auch die Kategorie und Schwierigkeit wählen
