### ISSUE TITLE
FallBackIntent (oder Alternative) umsetzen

### ISSUE THREAD

**Issue by RoodeyMental** [sweIhm-ws2018-19/skillproject-fr-34#50]
Da wir in der canHandle-Methode bestimmte boolean-Flags abfragen, kommt es vor, dass manchmal kein passender Handler zur Verfügung steht. Dafür müssen wir eine Möglichkeit finden das abzufangen, v.a. weil sich Alexa sonst in einem Zustand befindet in dem keine weiteren Eingaben möglich sind.

**Comment by Tosaa** [comment]
Ist das für Sprint 1 so wichtig ?
Ich dachte es gab so eine Aussage, wie der Benutzer versucht möglichst nicht gegen den Skill zu arbeiten. 

Können wir diesen Issue nach weiter hinten verlegen ?

**Comment by RoodeyMental** [comment]
Ja, wird nach hinten verlegt. Habe gelesen, dass der Intent nur in bestimmten Regionen verfügbar bist. Muss noch mit Frau Socher geklärt werden, ob man sich gegen komplett unsinnige Eingaben absichern muss.

**Comment by Tosaa** [comment]
Wie grade besprochen, ich kümmer mich darum.

**Comment by RoodeyMental** [comment]
FallBackIntent wurde zwar umgesetzt, dieser ist scheinbar aber nicht fehlerfrei implementiert. Problem wurde mit Frau Socher besprochen und ein Fehler bei unserer Implementierung quasi ausgeschlossen.
