### ISSUE TITLE
valueOf-Methode für Kategorie-Enum / Schwierigkeit-Enum umsetzen und statt switch-case verwenden

### ISSUE THREAD

**Issue by RoodeyMental** [sweIhm-ws2018-19/skillproject-fr-34#51]

**Comment by Tosaa** [comment]
Ich habe die ValueOf Methode für die Kategorien eingesetzt.
Für die Schwierigkeit habe ich eine weitere Methode gebaut die wir nutzen sollten, da es ja synonyme gibt. Also gibt es in dem dazugehörigen Enum eine weitere Methode und eine statische Map die die Synonyme auf das Enum Objekt mapt.
