### ISSUE TITLE
Antwortmöglichkeiten überarbeiten

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#57]
Die Antwort muss überarbeitet werden. 
Anstatt das der Spieler eine beliebige Antwort gegeben kann, muss er sich ab jetzt für a, b oder c entscheiden und "a", "b" oder "c" antworten um die vorgeschlagene Antwortmöglichkeit zu wählen. 

Alexa stellt die Frage:
"welche Tier ist Donald Duck? a Ente, b Tieger, c Fisch" 
Der Spieler Antwortet:
"a"

**Comment by RoodeyMental** [comment]
Wurde umgesetzt. Mit dem Signalwort "antwort" und anschließend der Antwortmöglichkeit(a, b, c) wurde die in der Sprint2 Doku beschriebene Problematik umgangen. Bitte reviewen und Funktionalität bestätigen.

**Comment by Tosaa** [comment]
funktioniert wie besprochen
