### ISSUE TITLE
Frage überarbeiten

### ISSUE THREAD

**Issue by Tosaa** [sweIhm-ws2018-19/skillproject-fr-34#58]
Die Fragestellung muss überarbeitet werden.

Die Fragestellung muss die Drei Antwortmöglichkeiten beinhalten. 
aktuell:
"welche Tier ist Donald Duck?"
neu:
"welche Tier ist Donald Duck? a Ente, b Tieger, c Fisch"

**Comment by Tosaa** [comment]
Dazu gehört auch im Frontend den Solution Intent zu überarbeiten.

**Comment by RoodeyMental** [comment]
Umgesetzt. Bitte reviewen.

**Comment by Tosaa** [comment]
umgesetzt
